#
#  Copyright 2015 VMware, Inc.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: create temp directory for content pack files
  file: dest=/var/content state=directory recurse=yes

- name: copy content packs to loginsight vm
  copy: src={{ item }} dest=/var/content
  with_fileglob:
    - "{{ vrli_ova_location }}/*.vlcp"

- name: install content packs
  script: copy_packs.sh

- name: restarting loginsight
  command: service loginsight restart

- name: Notice -- Waiting on VM availability.
  wait_for: port=9160 delay=30 timeout=300
