#
#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---

# Power off VMs if they're not already
- include: poweroff.yml

- name: deploy vRealize Log Insight master node
  shell: >
    {{ ovftool }}
    '--name={{ vrli_name }}'
    --acceptAllEulas
    --overwrite
    --allowExtraConfig
    --skipManifestCheck
    --noSSLVerify
    --diskMode=thin
    --deploymentOption={{ deployment_size }}
    '-ds={{ vrli_datastore }}'
    '--net:Network 1={{ vrli_network }}'
    --prop:vm.rootpw=VMware1!
    --prop:vm.rootpw.VMware_vCenter_Log_Insight=VMware1!
    '--prop:ip0={{ vrli_ip }}'
    '--prop:vami.gateway.VMware_vCenter_Log_Insight={{ vrli_gateway }}'
    '--prop:vami.DNS.VMware_vCenter_Log_Insight={{ vrli_dns }}'
    '--prop:vami.ip0.VMware_vCenter_Log_Insight={{ vrli_ip }}'
    '--prop:vami.netmask0.VMware_vCenter_Log_Insight={{ vrli_netmask }}'
    '--prop:vami.hostname.VMware_vCenter_Log_Insight={{ vrli_host_name }}'
    --ipAllocationPolicy={{ ip_policy }}
    '--powerOn={{ start_vm }}'
    '{{ vrli_ova_location }}/{{ vrli_ova }}'
    'vi://{{ mgmt_vc_username | urlencode }}:{{ mgmt_vc_password | urlencode }}@{{ mgmt_vc }}:443/{{ mgmt_vc_datacenter }}/host/{{ vrli_cluster }}'
  tags:
    - OVA

- name: deploy vRealize Log Insight worker nodes
  shell: >
    {{ ovftool }}
    '--name={{ vrli_name }}'
    --acceptAllEulas
    --overwrite
    --allowExtraConfig
    --skipManifestCheck
    --noSSLVerify
    --diskMode=thin
    --deploymentOption={{ deployment_size }}
    '-ds={{ vrli_datastore }}'
    '--net:Network 1={{ vrli_network }}'
    --prop:vm.rootpw=VMware1!
    --prop:vm.rootpw.VMware_vCenter_Log_Insight=VMware1!
    '--prop:ip0={{ item.vrli_ip }}'
    '--prop:vami.gateway.VMware_vCenter_Log_Insight={{ vrli_gateway }}'
    '--prop:vami.DNS.VMware_vCenter_Log_Insight={{ vrli_dns }}'
    '--prop:vami.ip0.VMware_vCenter_Log_Insight={{ item.vrli_ip }}'
    '--prop:vami.netmask0.VMware_vCenter_Log_Insight={{ vrli_netmask }}'
    '--prop:vami.hostname.VMware_vCenter_Log_Insight={{ item.vrli_host_name }}'
    --ipAllocationPolicy={{ ip_policy }}
    '--powerOn={{ start_vm }}'
    '{{ vrli_ova_location }}/{{ vrli_ova }}'
    'vi://{{ mgmt_vc_username | urlencode }}:{{ mgmt_vc_password | urlencode }}@{{ mgmt_vc }}:443/{{ mgmt_vc_datacenter }}/host/{{ vrli_cluster }}'
  tags:
    - OVA
  with_items:
    - { vrli_ip: '{{ vrli_ip_1 }}', vrli_host_name: '{{ vrli_host_name_1 }}', vrli_name: '{{ vrli_name_1 }}' }
    - { vrli_ip: '{{ vrli_ip_2 }}', vrli_host_name: '{{ vrli_host_name_2 }}', vrli_name: '{{ vrli_name_2 }}' }
  when: deployment_type == "clustered"

- name: Notice -- Waiting on master node avaiability.
  wait_for: host={{ vrli_ip }} port=80 timeout=600

- name: deploy local ssh public key to master node
  command: 'cat /home/vmware/.ssh/id_rsa.pub | ssh root@{{ item }} "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"'
  with_items:
    - "{{ vrli_ip }}"

- name: Notice -- Waiting on worker node avaiability.
  wait_for: host={{ vrli_ip_2 }} port=80 timeout=600
  when: deployment_type == "clustered"

# - name: deploy local ssh public key to worker nodes
#   command: 'cat /home/vmware/.ssh/id_rsa.pub | ssh root@{{ item }} "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"'
#   with_items:
#     - "{{ vrli_ip_1 }}"
#     - "{{ vrli_ip_2 }}"
#   when: deployment_type == "clustered"
