#
#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: Install pip modules
  pip: name="{{ item }}" state=latest
  with_items:
    - pysphere
