#
#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---

- include: installs.yml
  when: action == 'deploy'

- include: deploy.yml
  when: action == 'deploy'

- include: configure.yml
  when: action == 'configure'

- include: configure_worker.yml
  when: action == 'configure_workers' and deployment_type == 'clustered'

- include: content-packs.yml
  when: action == 'content'

- include: poweron.yml
  when: action == 'poweron'

- include: poweroff.yml
  when: action == 'poweroff'
