#
#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#

- name: Power off vRLI
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    guest: "{{ item }}"
    state: powered_off
  ignore_errors: True
  with_items:
    - "{{ vrli_name }}"
    - "{{ vrli_name_1 }}"
    - "{{ vrli_name_2 }}"
